import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";
import PlacesProvider from "@/components/providers/PlacesProvider";
import { LanguageProvider } from "@/lib/contexts/LanguageContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LanguageProvider>
          <PlacesProvider>
            <Header />
            <main>{children}</main>
            <Footer />
          </PlacesProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
